"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Item = { id: string; name: string; category: string; location: string; quantity: string; expiry?: string; status: string; icon: string; note?: string };
type Location = { id: string; name: string; parent_name: string | null; level: "space" | "place" };
const URL = "https://zhgvctajsfsmzuumbeqo.supabase.co"; const KEY = "sb_publishable_w7GE0EDAeaHeoCIx4v_e9g_UhiOqK6c";
const headers = { apikey: KEY, Authorization: `Bearer ${KEY}`, "Content-Type": "application/json" }; const code = "fuge-home";

export default function Home() {
  const [view, setView] = useState<"home" | "map" | "items" | "add" | "detail">("home"); const [items, setItems] = useState<Item[]>([]); const [locations, setLocations] = useState<Location[]>([]);
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Item | null>(null); const [draft, setDraft] = useState(""); const [category, setCategory] = useState("其他"); const [location, setLocation] = useState("");
  const [newName, setNewName] = useState(""); const [parent, setParent] = useState(""); const [addMode, setAddMode] = useState<"space" | "place" | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const [itemRes, locRes] = await Promise.all([fetch(`${URL}/rest/v1/items?household_code=eq.${code}&select=*&order=created_at.desc`, { headers }), fetch(`${URL}/rest/v1/locations?household_code=eq.${code}&select=*&order=created_at.asc`, { headers })]); if (!itemRes.ok || !locRes.ok) throw new Error(); setItems(await itemRes.json()); const savedLocations = await locRes.json() as Location[]; setLocations(savedLocations); if (!location && savedLocations[0]) setLocation(savedLocations.find((entry) => entry.level === "place")?.name || savedLocations[0].name); setError(""); } catch { setError("云端地图尚未建立。请在 Supabase SQL Editor 执行最新的 schema.sql。") } }, [location]);
  useEffect(() => { const first = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(), 12000); return () => { clearTimeout(first); clearInterval(timer); }; }, [load]);
  const spaces = locations.filter((entry) => entry.level === "space"); const places = locations.filter((entry) => entry.level === "place"); const shownItems = useMemo(() => items.filter((item) => `${item.name}${item.category}${item.location}`.includes(query.trim())), [items, query]);
  const api = async (path: string, init?: RequestInit) => { const res = await fetch(`${URL}/rest/v1/${path}`, { ...init, headers: { ...headers, ...(init?.headers || {}) } }); if (!res.ok) throw new Error(); return res; };
  const saveItem = async (e: FormEvent) => { e.preventDefault(); try { const payload = { household_code: code, name: draft.trim() || "未命名物品", category, location, quantity: "1 件", status: "未开封", icon: "📦", note: "由快速记录创建。" }; const res = await api("items", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); const [item] = await res.json() as Item[]; setItems((v) => [item, ...v]); setSelected(item); setDraft(""); setMessage("已同步给福哥的家成员。"); setView("detail"); } catch { setError("保存失败，请先执行 schema.sql。") } };
  const createLocation = async (e: FormEvent) => { e.preventDefault(); if (!newName.trim() || !addMode) return; try { const payload = { household_code: code, name: newName.trim(), parent_name: addMode === "place" ? parent : null, level: addMode }; await api("locations", { method: "POST", body: JSON.stringify(payload) }); setNewName(""); setParent(""); setAddMode(null); await load(); } catch { setError("保存空间失败，请检查名称是否重复或重新执行 schema.sql。") } };
  const renameLocation = async (entry: Location) => { const next = window.prompt("修改名称", entry.name)?.trim(); if (!next || next === entry.name) return; try { await api(`locations?id=eq.${entry.id}`, { method: "PATCH", body: JSON.stringify({ name: next }) }); if (entry.level === "space") { await api(`locations?parent_name=eq.${encodeURIComponent(entry.name)}`, { method: "PATCH", body: JSON.stringify({ parent_name: next }) }); } await load(); } catch { setError("修改失败，请稍后重试。") } };
  const deleteLocation = async (entry: Location) => { const contained = entry.level === "space" ? places.some((p) => p.parent_name === entry.name) : items.some((item) => item.location.includes(entry.name)); if (contained) { setError(`“${entry.name}”仍有关联收纳地点或物品，请先移动/归档后再删除。`); return; } if (!window.confirm(`确定删除“${entry.name}”吗？`)) return; try { await api(`locations?id=eq.${entry.id}`, { method: "DELETE" }); await load(); } catch { setError("删除失败，请稍后重试。") } };
  const archive = async () => { if (!selected) return; try { await api(`items?id=eq.${selected.id}`, { method: "DELETE" }); setItems((v) => v.filter((item) => item.id !== selected.id)); setView("items"); } catch { setError("归档失败，请稍后重试。") } };
  return <main className="app-shell"><header className="topbar"><button className="brand" onClick={() => setView("home")}><span className="brand-cat" /> 福哥的家</button><div className="family-chip"><span className="avatar">D</span> 共同收纳</div></header><section className="page">{error && <div className="sync-error">{error}</div>}
    {view === "home" && <><div className="welcome hero"><div><p className="eyebrow">共同收纳空间</p><h1>家里的每样东西，<br/>大福都记得住。</h1><p>全家共同记录、共同查找。</p></div><span className="cat-mascot" /></div><label className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} onFocus={() => setView("items")} placeholder="搜索物品或收纳位置" /></label><div className="room-strip">{spaces.slice(0, 4).map((space) => <button key={space.id} onClick={() => setView("map")}><span>⌂</span>{space.name}</button>)}</div><div className="action-grid"><button className="primary-action" onClick={() => setView("items")}><b>⌕</b><span><strong>物品搜索</strong><small>搜索家里的所有物品</small></span></button><button className="primary-action voice-action" onClick={() => setView("add")}><b>＋</b><span><strong>快速录入</strong><small>新增后自动同步给家人</small></span></button></div><section className="section"><div className="section-head"><h2>最近记录</h2><button onClick={() => setView("items")}>全部物品</button></div><div className="item-list">{items.length ? items.slice(0, 3).map((item) => <ItemRow key={item.id} item={item} onClick={() => { setSelected(item); setView("detail"); }} />) : <div className="empty"><strong>还没有物品记录</strong><p>先添加家里的第一件物品吧。</p></div>}</div></section></>}
    {view === "map" && <><div className="page-title"><div><p className="eyebrow">家庭空间</p><h1>收纳地图</h1><p>和家人一起维护家的每个角落。</p></div><button className="round-add" onClick={() => setAddMode("space")}>＋</button></div><div className="map-actions"><button onClick={() => setAddMode("space")}>＋ 添加空间</button><button onClick={() => { setParent(spaces[0]?.name || ""); setAddMode("place"); }}>＋ 添加收纳地点</button></div>{addMode && <form className="location-form" onSubmit={createLocation}><strong>{addMode === "space" ? "添加家庭空间" : "添加收纳地点"}</strong><input value={newName} onChange={(e) => setNewName(e.target.value)} placeholder={addMode === "space" ? "例如：主卧、储物间" : "例如：衣柜上层、床下收纳箱"} autoFocus />{addMode === "place" && <select value={parent} onChange={(e) => setParent(e.target.value)}>{spaces.map((space) => <option key={space.id}>{space.name}</option>)}</select>}<div><button type="button" onClick={() => setAddMode(null)}>取消</button><button className="save-small" type="submit">保存</button></div></form>}<div className="map-card">{spaces.map((space) => { const children = places.filter((place) => place.parent_name === space.name); return <div className="location-group" key={space.id}><div className="location-room"><span>⌂</span><strong>{space.name}</strong><small>{children.length} 个收纳地点</small><button onClick={() => renameLocation(space)}>编辑</button><button onClick={() => deleteLocation(space)}>删除</button></div>{children.map((place) => <div className="location-node" key={place.id}><button onClick={() => { setLocation(`${space.name} · ${place.name}`); setView("items"); }}><span>└</span>{place.name}</button><em><button onClick={() => renameLocation(place)}>编辑</button><button onClick={() => deleteLocation(place)}>删除</button></em></div>)}</div>; })}</div></>}
    {view === "items" && <><div className="page-title compact"><div><p className="eyebrow">家庭物品库</p><h1>所有物品</h1></div><button className="round-add" onClick={() => setView("add")}>＋</button></div><label className="search"><span>⌕</span><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索物品、位置或类别" /></label><div className="item-list full">{shownItems.length ? shownItems.map((item) => <ItemRow key={item.id} item={item} onClick={() => { setSelected(item); setView("detail"); }} />) : <div className="empty"><strong>没有找到相关物品</strong><p>换个词试试，或添加一条新记录。</p></div>}</div></>}
    {view === "add" && <><button className="back" onClick={() => setView("home")}>‹ 返回</button><div className="page-title compact"><div><p className="eyebrow">快速记录</p><h1>记下新物品</h1><p>保存后会同步给福哥的家成员。</p></div></div><form onSubmit={saveItem} className="record-form"><label><span>物品名称或描述</span><textarea value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="例如：两瓶洗衣液放在阳台洗衣柜下层" autoFocus /></label><label><span>物品类别</span><select value={category} onChange={(e) => setCategory(e.target.value)}><option>其他</option><option>清洁</option><option>药品</option><option>食品</option><option>工具</option><option>数码</option></select></label><label><span>收纳位置</span><select value={location} onChange={(e) => setLocation(e.target.value)}>{places.map((place) => <option key={place.id} value={`${place.parent_name} · ${place.name}`}>{place.parent_name} · {place.name}</option>)}</select></label><button className="save" type="submit">确认并同步</button></form></>}
    {view === "detail" && selected && <><button className="back" onClick={() => setView("items")}>‹ 返回物品库</button><article className="detail"><div className="item-hero"><span>{selected.icon}</span><div><p className="eyebrow">{selected.category}</p><h1>{selected.name}</h1><p>{selected.quantity} · {selected.status}</p></div></div>{message && <p className="toast">✓ {message}</p>}<div className="detail-card"><p className="label">收纳位置</p><strong className="path">{selected.location}</strong></div><div className="detail-actions"><button className="danger" onClick={archive}>归档这件物品</button></div></article></>}
  </section><nav className="bottom-nav"><button className={view === "home" ? "selected" : ""} onClick={() => setView("home")}><span>⌂</span>首页</button><button className={view === "map" ? "selected" : ""} onClick={() => setView("map")}><span>⌘</span>地图</button><button className="nav-plus" onClick={() => setView("add")}>＋</button><button className={view === "items" || view === "detail" ? "selected" : ""} onClick={() => setView("items")}><span>▦</span>物品</button><button><span>◉</span>我的</button></nav></main>;
}
function ItemRow({ item, onClick }: { item: Item; onClick: () => void }) { return <button className="item-row" onClick={onClick}><span className="item-icon">{item.icon}</span><span className="item-info"><strong>{item.name}</strong><small>{item.location}</small></span><span className="item-meta"><b>{item.quantity}</b><small>{item.status}</small></span><span className="arrow">›</span></button>; }
