"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Item = { id: string; name: string; category: string; location: string; quantity: string; expiry?: string; status: string; icon: string; note?: string };
type DbItem = Item & { household_code: string; created_at: string };

const SUPABASE_URL = "https://zhgvctajsfsmzuumbeqo.supabase.co";
const SUPABASE_KEY = "sb_publishable_w7GE0EDAeaHeoCIx4v_e9g_UhiOqK6c";
const headers = { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, "Content-Type": "application/json" };

const locations = [["客厅", ["电视柜", "茶几收纳格"]], ["厨房", ["冰箱", "水槽下柜", "调料抽屉"]], ["阳台", ["洗衣柜", "清洁杂物柜"]], ["书房", ["书桌抽屉", "工具箱"]], ["玄关", ["玄关柜", "鞋柜"]]];

export default function Home() {
  const [view, setView] = useState<"home" | "map" | "items" | "add" | "detail">("home");
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Item | null>(null); const [draft, setDraft] = useState(""); const [category, setCategory] = useState("其他");
  const [location, setLocation] = useState("阳台 · 洗衣柜"); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const loadItems = useCallback(async () => { try { const response = await fetch(`${SUPABASE_URL}/rest/v1/items?household_code=eq.fuge-home&select=*&order=created_at.desc`, { headers }); if (!response.ok) throw new Error(); setItems(await response.json()); setError(""); } catch { setError("还没有连接到家庭物品库。请先按项目里的 supabase/schema.sql 创建数据表。"); } finally { setLoading(false); } }, []);
  useEffect(() => { const firstLoad = window.setTimeout(() => { void loadItems(); }, 0); const timer = window.setInterval(() => { void loadItems(); }, 12000); return () => { window.clearTimeout(firstLoad); window.clearInterval(timer); }; }, [loadItems]);
  const shownItems = useMemo(() => items.filter((item) => `${item.name}${item.category}${item.location}`.includes(query.trim())), [items, query]);
  const showDetail = (item: Item) => { setSelected(item); setMessage(""); setView("detail"); };
  const saveItem = async (event: FormEvent) => { event.preventDefault(); const name = draft.trim() || "未命名物品"; const payload = { household_code: "fuge-home", name, category, location, quantity: "1 件", status: "未开封", icon: "📦", note: "由快速记录创建。" }; try { const response = await fetch(`${SUPABASE_URL}/rest/v1/items`, { method: "POST", headers: { ...headers, Prefer: "return=representation" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(); const [item] = await response.json() as DbItem[]; setItems((current) => [item, ...current]); setSelected(item); setDraft(""); setMessage("已同步到福哥的家，家人刷新后即可看到。"); setView("detail"); } catch { setError("保存失败：请确认已在 Supabase 执行 schema.sql。") } };
  const archiveItem = async () => { if (!selected) return; try { const response = await fetch(`${SUPABASE_URL}/rest/v1/items?id=eq.${selected.id}`, { method: "DELETE", headers }); if (!response.ok) throw new Error(); setItems((current) => current.filter((item) => item.id !== selected.id)); setView("items"); } catch { setError("归档失败，请检查网络后重试。") } };
  return <main className="app-shell"><header className="topbar"><button className="brand" onClick={() => setView("home")}><span className="brand-cat" /> 福哥的家</button><div className="family-chip"><span className="avatar">D</span> 共同收纳 <span className="chev">⌄</span></div></header><section className="page">{error && <div className="sync-error">{error}</div>}
    {view === "home" && <><div className="welcome hero"><div><p className="eyebrow">共同收纳空间</p><h1>家里的每样东西，<br/>大福都记得住。</h1><p>全家共同记录、共同查找。</p></div><span className="cat-mascot" aria-label="大福猫咪" /></div><label className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索物品或收纳位置" onFocus={() => setView("items")} /></label><div className="room-strip"><button onClick={() => setView("map")}><span>🛋</span>客厅收纳</button><button onClick={() => setView("map")}><span>🍳</span>厨房收纳</button><button onClick={() => setView("map")}><span>🧺</span>阳台收纳</button></div><div className="action-grid"><button className="primary-action" onClick={() => setView("items")}><b>⌕</b><span><strong>物品搜索</strong><small>搜索家里的所有物品</small></span></button><button className="primary-action voice-action" onClick={() => setView("add")}><b>＋</b><span><strong>快速录入</strong><small>新增后自动同步给家人</small></span></button></div><section className="section"><div className="section-head"><h2>最近记录</h2><button onClick={() => setView("items")}>全部物品</button></div><div className="item-list">{loading ? <div className="empty">正在连接家庭物品库…</div> : items.length ? items.slice(0, 3).map((item) => <ItemRow key={item.id} item={item} onClick={() => showDetail(item)} />) : <div className="empty"><strong>还没有物品记录</strong><p>先添加家里的第一件物品吧。</p></div>}</div></section></>}
    {view === "map" && <><div className="page-title"><div><p className="eyebrow">家庭空间</p><h1>收纳地图</h1><p>从房间到抽屉，记住每个位置。</p></div><button className="round-add" onClick={() => setView("add")}>＋</button></div><div className="map-card">{locations.map(([room, children]) => <div className="location-group" key={room as string}><div className="location-room"><span>⌂</span><strong>{room as string}</strong><small>{(children as string[]).length} 个收纳地点</small></div>{(children as string[]).map((place) => <button key={place} className="location-node" onClick={() => { setLocation(`${room} · ${place}`); setView("items"); }}><span>└</span>{place}<em>›</em></button>)}</div>)}</div></>}
    {view === "items" && <><div className="page-title compact"><div><p className="eyebrow">家庭物品库</p><h1>所有物品</h1></div><button className="round-add" onClick={() => setView("add")}>＋</button></div><label className="search"><span>⌕</span><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索物品、位置或类别" /></label><div className="item-list full">{shownItems.length ? shownItems.map((item) => <ItemRow key={item.id} item={item} onClick={() => showDetail(item)} />) : <div className="empty"><strong>{loading ? "正在加载…" : "没有找到相关物品"}</strong><p>换个词试试，或添加一条新记录。</p></div>}</div></>}
    {view === "add" && <><button className="back" onClick={() => setView("home")}>‹ 返回</button><div className="page-title compact"><div><p className="eyebrow">快速记录</p><h1>记下新物品</h1><p>保存后会同步给福哥的家成员。</p></div></div><form onSubmit={saveItem} className="record-form"><label><span>物品名称或描述</span><textarea value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="例如：两瓶洗衣液放在阳台洗衣柜下层" autoFocus /></label><label><span>物品类别</span><select value={category} onChange={(e) => setCategory(e.target.value)}><option>其他</option><option>清洁</option><option>药品</option><option>食品</option><option>工具</option><option>数码</option></select></label><label><span>收纳位置</span><select value={location} onChange={(e) => setLocation(e.target.value)}>{locations.flatMap(([room, places]) => (places as string[]).map((place) => <option key={`${room}-${place}`}>{room} · {place}</option>))}</select></label><button className="save" type="submit">确认并同步</button></form></>}
    {view === "detail" && selected && <><button className="back" onClick={() => setView("items")}>‹ 返回物品库</button><article className="detail"><div className="item-hero"><span>{selected.icon}</span><div><p className="eyebrow">{selected.category}</p><h1>{selected.name}</h1><p>{selected.quantity} · {selected.status}</p></div></div>{message && <p className="toast">✓ {message}</p>}<div className="detail-card"><p className="label">收纳位置</p><strong className="path">{selected.location}</strong></div><div className="detail-card"><p className="label">记录说明</p><p>{selected.note || "这件物品已记录在家庭物品库中。"}</p></div><div className="detail-actions"><button className="danger" onClick={archiveItem}>归档这件物品</button></div></article></>}
  </section><nav className="bottom-nav"><button className={view === "home" ? "selected" : ""} onClick={() => setView("home")}><span>⌂</span>首页</button><button className={view === "map" ? "selected" : ""} onClick={() => setView("map")}><span>⌘</span>地图</button><button className="nav-plus" onClick={() => setView("add")}>＋</button><button className={view === "items" || view === "detail" ? "selected" : ""} onClick={() => setView("items")}><span>▦</span>物品</button><button><span>◉</span>我的</button></nav></main>;
}

function ItemRow({ item, onClick }: { item: Item; onClick: () => void }) { return <button className="item-row" onClick={onClick}><span className="item-icon">{item.icon}</span><span className="item-info"><strong>{item.name}</strong><small>{item.location}</small></span><span className="item-meta"><b>{item.quantity}</b><small>{item.expiry ? `有效期 ${item.expiry}` : item.status}</small></span><span className="arrow">›</span></button>; }
