"use client";

import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import restIcon from "./assets/dafu/rest.png";
import happyIcon from "./assets/dafu/happy.png";
import angryIcon from "./assets/dafu/angry.png";
import heartIcon from "./assets/dafu/heart.png";
import watermelonIcon from "./assets/dafu/watermelon.png";
import peekIcon from "./assets/dafu/peek.png";
import footIcon from "./assets/dafu/foot.png";

type Item = { id: string; name: string; category: string; location: string; quantity: string; expiry?: string; status: string; icon: string; note?: string; image_url?: string };
type Location = { id: string; name: string; parent_name: string | null; level: "space" | "place" };
const URL = "https://zhgvctajsfsmzuumbeqo.supabase.co"; const KEY = "sb_publishable_w7GE0EDAeaHeoCIx4v_e9g_UhiOqK6c"; const code = "fuge-home";
const baseHeaders = { apikey: KEY, "Content-Type": "application/json" };

export default function Home() {
  const [view, setView] = useState<"home"|"map"|"items"|"add"|"detail"|"me">("home"); const [items, setItems] = useState<Item[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Item | null>(null);
  const [draft, setDraft] = useState(""); const [category, setCategory] = useState("其他"); const [location, setLocation] = useState(""); const [expiry, setExpiry] = useState(""); const [photo, setPhoto] = useState<File | null>(null); const [photoPreview, setPhotoPreview] = useState("");
  const [newName, setNewName] = useState(""); const [parent, setParent] = useState(""); const [addMode, setAddMode] = useState<"space"|"place"|null>(null); const [editing, setEditing] = useState<Location | null>(null); const [editName, setEditName] = useState("");
  const [memberName, setMemberName] = useState(""); const [avatar, setAvatar] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const api = async (path: string, init?: RequestInit) => { const response = await fetch(`${URL}/rest/v1/${path}`, { ...init, headers: { ...baseHeaders, Authorization: `Bearer ${KEY}`, ...(init?.headers || {}) } }); if (!response.ok) throw new Error(); return response; };
  const load = useCallback(async () => { try { const headers = { ...baseHeaders, Authorization: `Bearer ${localStorage.getItem("fuge-token") || KEY}` }; const [itemRes, locRes] = await Promise.all([fetch(`${URL}/rest/v1/items?household_code=eq.${code}&select=*&order=created_at.desc`, { headers }), fetch(`${URL}/rest/v1/locations?household_code=eq.${code}&select=*&order=created_at.asc`, { headers })]); if (!itemRes.ok || !locRes.ok) throw new Error(); setItems(await itemRes.json()); const list = await locRes.json() as Location[]; setLocations(list); if (!location) setLocation(list.find((entry) => entry.level === "place") ? `${list.find((entry) => entry.level === "place")?.parent_name} · ${list.find((entry) => entry.level === "place")?.name}` : ""); setError(""); } catch { setError("云端地图尚未建立。请先执行 SQL 升级脚本。"); } }, [location]);
  useEffect(() => { const start = setTimeout(() => { void load(); setMemberName(localStorage.getItem("fuge-member-name") || ""); setAvatar(localStorage.getItem("fuge-avatar") || ""); }, 0); const timer = setInterval(() => void load(), 12000); return () => { clearTimeout(start); clearInterval(timer); }; }, [load]);
  const spaces = locations.filter((entry) => entry.level === "space"); const places = locations.filter((entry) => entry.level === "place"); const shownItems = useMemo(() => items.filter((item) => `${item.name}${item.category}${item.location}`.includes(query.trim())), [items, query]);
  const handlePhoto = (event: ChangeEvent<HTMLInputElement>, target: "item"|"avatar") => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const data = String(reader.result); if (target === "item") { setPhoto(file); setPhotoPreview(data); } else { setAvatar(data); localStorage.setItem("fuge-avatar", data); } }; reader.readAsDataURL(file); };
  const uploadPhoto = async () => { if (!photo) return ""; const safe = photo.name.replace(/[^a-zA-Z0-9._-]/g, "-"); const path = `fuge-home/${photo.lastModified}-${safe}`; const response = await fetch(`${URL}/storage/v1/object/fuge-images/${path}`, { method: "POST", headers: { apikey: KEY, Authorization: `Bearer ${KEY}`, "x-upsert": "true", "Content-Type": photo.type }, body: photo }); if (!response.ok) throw new Error(); return `${URL}/storage/v1/object/public/fuge-images/${path}`; };
  const saveItem = async (event: FormEvent) => { event.preventDefault(); try { const image_url = await uploadPhoto(); const payload = { household_code: code, name: draft.trim() || "未命名物品", category, location, quantity: "1 件", status: "未开封", icon: "📦", note: "由快速记录创建。", image_url: image_url || null, expiry: expiry || null }; const response = await api("items", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); const [item] = await response.json() as Item[]; setItems((value) => [item, ...value]); setSelected(item); setDraft(""); setExpiry(""); setPhoto(null); setPhotoPreview(""); setMessage("已同步给福哥的家成员。"); setView("detail"); } catch { setError("保存失败：请先执行 V2 SQL 升级脚本。") } };
  const createLocation = async (event: FormEvent) => { event.preventDefault(); if (!newName.trim() || !addMode) return; try { await api("locations", { method: "POST", body: JSON.stringify({ household_code: code, name: newName.trim(), parent_name: addMode === "place" ? parent : null, level: addMode }) }); setNewName(""); setAddMode(null); await load(); } catch { setError("保存空间失败，请稍后重试。") } };
  const saveRename = async (event: FormEvent) => { event.preventDefault(); if (!editing || !editName.trim()) return; try { const next = editName.trim(); await api(`locations?id=eq.${editing.id}`, { method: "PATCH", body: JSON.stringify({ name: next }) }); if (editing.level === "space") await api(`locations?parent_name=eq.${encodeURIComponent(editing.name)}`, { method: "PATCH", body: JSON.stringify({ parent_name: next }) }); setEditing(null); await load(); } catch { setError("修改失败，请稍后重试。") } };
  const deleteLocation = async (entry: Location) => { const linked = entry.level === "space" ? places.some((place) => place.parent_name === entry.name) : items.some((item) => item.location.includes(entry.name)); if (linked) return setError(`“${entry.name}”仍有关联内容，请先移动或归档后再删除。`); if (!confirm(`确定删除“${entry.name}”吗？`)) return; try { await api(`locations?id=eq.${entry.id}`, { method: "DELETE" }); await load(); } catch { setError("删除失败。") } };
  const archive = async () => { if (!selected) return; try { await api(`items?id=eq.${selected.id}`, { method: "DELETE" }); setItems((value) => value.filter((item) => item.id !== selected.id)); setView("items"); } catch { setError("归档失败。") } };
  const saveMember = () => { const name = memberName.trim() || "家人"; setMemberName(name); localStorage.setItem("fuge-member-name", name); setMessage("个人资料已保存在这台设备。"); };
  return <main className="app-shell"><header className="topbar"><button className="brand" onClick={() => setView("home")}><img className="brand-cat" src={happyIcon.src} alt="大福" /> 福哥的家</button><button className="family-chip" onClick={() => setView("me")}><span className="avatar">{avatar ? <img src={avatar} alt="头像" /> : <img src={heartIcon.src} alt="大福" />}</span>{memberName || "共同收纳"}</button></header><section className="page">{error && <div className="sync-error">{error}</div>}
    {view === "home" && <><div className="welcome hero"><div><p className="eyebrow">共同收纳空间</p><h1>家里的每样东西，<br/>大福都记得住。</h1><p>全家共同记录、共同查找。</p></div><img className="cat-mascot" src={heartIcon.src} alt="大福" /></div><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} onFocus={() => setView("items")} placeholder="搜索物品或收纳位置" /></label><div className="room-strip">{spaces.slice(0, 4).map((space, index) => <button key={space.id} onClick={() => setView("map")}><img className="room-dafu" src={[restIcon, happyIcon, watermelonIcon, peekIcon][index % 4].src} alt="大福" />{space.name}</button>)}</div><div className="action-grid"><button className="primary-action" onClick={() => setView("items")}><img className="action-dafu" src={angryIcon.src} alt="大福" /><span><strong>物品搜索</strong><small>搜索家里的所有物品</small></span></button><button className="primary-action voice-action" onClick={() => setView("add")}><img className="action-dafu" src={happyIcon.src} alt="大福" /><span><strong>快速录入</strong><small>新增后自动同步给家人</small></span></button></div><section className="section"><div className="section-head"><h2>最近记录</h2><button onClick={() => setView("items")}>全部物品</button></div><div className="item-list">{items.length ? items.slice(0, 3).map((item) => <ItemRow key={item.id} item={item} onClick={() => { setSelected(item); setView("detail"); }} />) : <div className="empty"><strong>还没有物品记录</strong><p>先添加家里的第一件物品吧。</p></div>}</div></section></>}
    {view === "map" && <><div className="page-title"><div><p className="eyebrow">家庭空间</p><h1>收纳地图</h1><p>和家人一起维护家的每个角落。</p></div><button className="round-add" onClick={() => setAddMode("space")}>＋</button></div><div className="map-actions"><button onClick={() => setAddMode("space")}>＋ 添加空间</button><button onClick={() => { setParent(spaces[0]?.name || ""); setAddMode("place"); }}>＋ 添加收纳地点</button></div>{addMode && <form className="location-form" onSubmit={createLocation}><strong>{addMode === "space" ? "添加家庭空间" : "添加收纳地点"}</strong><input value={newName} onChange={(event) => setNewName(event.target.value)} placeholder={addMode === "space" ? "例如：主卧、储物间" : "例如：衣柜上层、床下收纳箱"} autoFocus />{addMode === "place" && <select value={parent} onChange={(event) => setParent(event.target.value)}>{spaces.map((space) => <option key={space.id}>{space.name}</option>)}</select>}<FormActions onCancel={() => setAddMode(null)} saveText="保存" /></form>}{editing && <form className="location-form edit-form" onSubmit={saveRename}><strong>修改{editing.level === "space" ? "空间" : "收纳地点"}</strong><input value={editName} onChange={(event) => setEditName(event.target.value)} autoFocus /><FormActions onCancel={() => setEditing(null)} saveText="保存修改" /></form>}<div className="map-card">{spaces.map((space) => { const children = places.filter((place) => place.parent_name === space.name); return <div className="location-group" key={space.id}><div className="location-room"><div className="location-name"><span>⌂</span><strong>{space.name}</strong><small>{children.length} 个收纳地点</small></div><div className="location-controls"><button onClick={() => { setEditing(space); setEditName(space.name); }}>编辑</button><button onClick={() => deleteLocation(space)}>删除</button></div></div>{children.map((place) => <div className="location-node" key={place.id}><button onClick={() => { setLocation(`${space.name} · ${place.name}`); setView("items"); }}><span>└</span>{place.name}</button><em><button onClick={() => { setEditing(place); setEditName(place.name); }}>编辑</button><button onClick={() => deleteLocation(place)}>删除</button></em></div>)}</div>; })}</div></>}
    {view === "items" && <><div className="page-title compact"><div><p className="eyebrow">家庭物品库</p><h1>所有物品</h1></div><button className="round-add" onClick={() => setView("add")}>＋</button></div><label className="search"><span>⌕</span><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索物品、位置或类别" /></label><div className="item-list full">{shownItems.length ? shownItems.map((item) => <ItemRow key={item.id} item={item} onClick={() => { setSelected(item); setView("detail"); }} />) : <div className="empty"><strong>没有找到相关物品</strong><p>换个词试试，或添加一条新记录。</p></div>}</div></>}
    {view === "add" && <><button className="back" onClick={() => setView("home")}>‹ 返回</button><div className="page-title compact"><div><p className="eyebrow">快速记录</p><h1>记下新物品</h1><p>保存后会同步给福哥的家成员。</p></div></div><form onSubmit={saveItem} className="record-form"><label><span>物品名称或描述</span><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="例如：两瓶洗衣液放在阳台洗衣柜下层" autoFocus /></label><label className="photo-upload"><span>物品照片</span><input type="file" accept="image/*" capture="environment" onChange={(event) => handlePhoto(event, "item")} />{photoPreview && <img src={photoPreview} alt="物品预览" />}</label><label><span>物品类别</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option>其他</option><option>清洁</option><option>药品</option><option>食品</option><option>工具</option><option>数码</option></select></label><label><span>收纳位置</span><select value={location} onChange={(event) => setLocation(event.target.value)}>{places.map((place) => <option key={place.id} value={`${place.parent_name} · ${place.name}`}>{place.parent_name} · {place.name}</option>)}</select></label><label><span>保质期（可选）</span><input type="date" value={expiry} onChange={(event) => setExpiry(event.target.value)} /></label><button className="save" type="submit">确认并同步</button></form></>}
    {view === "detail" && selected && <><button className="back" onClick={() => setView("items")}>‹ 返回物品库</button><article className="detail">{selected.image_url && <img className="item-photo" src={selected.image_url} alt={selected.name} />}<div className="item-hero"><span>{selected.icon}</span><div><p className="eyebrow">{selected.category}</p><h1>{selected.name}</h1><p>{selected.quantity} · {selected.status}</p></div></div>{message && <p className="toast">✓ {message}</p>}<div className="detail-card"><p className="label">收纳位置</p><strong className="path">{selected.location}</strong></div><div className="detail-card"><p className="label">保质期</p><strong>{selected.expiry || "未记录"}</strong></div><div className="detail-actions"><button className="danger" onClick={archive}>归档这件物品</button></div></article></>}
    {view === "me" && <><button className="back" onClick={() => setView("home")}>‹ 返回</button><div className="page-title compact"><div><p className="eyebrow">我的</p><h1>我的家庭资料</h1><p>仅在本机保存昵称和头像，无需邮箱注册。</p></div></div><section className="account-card"><label className="avatar-picker"><span className="large-avatar">{avatar ? <img src={avatar} alt="头像" /> : <img src={footIcon.src} alt="大福" />}</span><input type="file" accept="image/*" onChange={(event) => handlePhoto(event, "avatar")} /><b>选择头像照片</b></label><label><span>昵称</span><input value={memberName} onChange={(event) => setMemberName(event.target.value)} placeholder="例如：福哥" /></label><button className="profile-save" onClick={saveMember}>保存我的资料</button></section></>}
  </section><nav className="bottom-nav"><button className={view === "home" ? "selected" : ""} onClick={() => setView("home")}><img src={restIcon.src} alt="" />首页</button><button className={view === "map" ? "selected" : ""} onClick={() => setView("map")}><img src={peekIcon.src} alt="" />地图</button><button className="nav-plus" onClick={() => setView("add")}><img src={happyIcon.src} alt="" /></button><button className={view === "items" || view === "detail" ? "selected" : ""} onClick={() => setView("items")}><img src={watermelonIcon.src} alt="" />物品</button><button className={view === "me" ? "selected" : ""} onClick={() => setView("me")}><img src={heartIcon.src} alt="" />我的</button></nav></main>;
}
function FormActions({ onCancel, saveText }: { onCancel: () => void; saveText: string }) { return <div><button type="button" onClick={onCancel}>取消</button><button className="save-small" type="submit">{saveText}</button></div>; }
function ItemRow({ item, onClick }: { item: Item; onClick: () => void }) { return <button className="item-row" onClick={onClick}>{item.image_url ? <img className="item-thumb" src={item.image_url} alt="" /> : <span className="item-icon">{item.icon}</span>}<span className="item-info"><strong>{item.name}</strong><small>{item.location}</small></span><span className="item-meta"><b>{item.quantity}</b><small>{item.expiry ? `至 ${item.expiry}` : item.status}</small></span><span className="arrow">›</span></button>; }
